### ISSUE TITLE
Paleta de colores : Clientes

### ISSUE THREAD

**Issue by Cyzzaro** [Cyzzaro/investigacion.ciasc.mx-php#1]
:art: Definir la paleta de colores de cada cliente en base a su logotipo tomando como base los 5 elementos representativos.
Usar la forma

### Cliente
![2015-04-22_17-19-13_screenshot-www pictaculous com](https://cloud.githubusercontent.com/assets/9372970/7286792/38698edc-e914-11e4-838b-27e401bc1abe.png)
```css
#3EFFFF #F8000D #23C8EF #0068B5 #000000 
```

**Comment by Cyzzaro** [comment]
## Arccanto
```css
Arccanto {
	color: #000000;
	color: #2C9CDD;
	color: #36255D;
	color: #DBD6E5;
}
```
![2015-04-22_16-39-43_screenshot-www pictaculous com](https://cloud.githubusercontent.com/assets/9372970/7286073/bf57f038-e90e-11e4-9d76-26d613f5c6ee.png)

**Comment by Cyzzaro** [comment]
## Banamex
```css
Banamex {
	color: #B7FFFF;
	color: #0F3761;
	color: #E1091D;
	color: #000000;
	color: #06315C;
}
```
![2015-04-22_16-55-22_screenshot-www pictaculous com](https://cloud.githubusercontent.com/assets/9372970/7286332/e0f26b40-e910-11e4-8df5-2c4dc1f81cc4.png)

**Comment by Cyzzaro** [comment]
## Bancomer
```css
Bancomer {
	color: #426DA2;
	color: #95ADCB;
	color: #F3F6F9;
	color: #000000;
	color: #074085;
}
```
![2015-04-22_16-58-18_screenshot-www pictaculous com](https://cloud.githubusercontent.com/assets/9372970/7286406/56c6cb7c-e911-11e4-85e0-a85cdd4389bb.png)

**Comment by Cyzzaro** [comment]
## Banorte
```css
Banorte {
	color: #781E20;
	color: #708D8A;
	color: #FFFFFF;
	color: #2D5753;
	color: #771D1F;
}
```
![2015-04-22_16-59-41_screenshot-www pictaculous com](https://cloud.githubusercontent.com/assets/9372970/7286441/9880dbca-e911-11e4-8562-24a768543024.png)

**Comment by Cyzzaro** [comment]
## Cemex
```css
Cemex {
	color: #494750;
	color: #6B6C6F;
	color: #EE3942;
	color: #003D7C;
	color: #000000;
}
```
![2015-04-22_17-02-03_screenshot-www pictaculous com](https://cloud.githubusercontent.com/assets/9372970/7286484/f1707dbc-e911-11e4-92aa-596b7c7f64b0.png)

**Comment by Cyzzaro** [comment]
## CNH
```css
CNH {
	color: #FF330F;
	color: #202C33;
	color: #000000;
	color: #202B32;
	color: #BF311A;
}
```
![2015-04-22_17-09-30_screenshot-www pictaculous com](https://cloud.githubusercontent.com/assets/9372970/7286634/0d1d7550-e913-11e4-8441-4e9d4d24dd48.png)

**Comment by Cyzzaro** [comment]
## DeLageLanden
```css
DeLageLanden {
	color: #BABCBE;
	color: #656A6E;
	color: #666A6D;
	color: #000000;
	color: #009FD7;
}
```
![2015-04-22_17-11-59_screenshot-www pictaculous com](https://cloud.githubusercontent.com/assets/9372970/7286673/4f1c5b88-e913-11e4-85c8-8365cec8a27e.png)
